name: Sync Fork Automático

on:
  schedule:
    - cron: '0 * * * *' # Roda a cada hora
  workflow_dispatch: # Permite rodar manual

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Sync Upstream
        # Essa aqui é a ferramenta oficial do GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh repo sync pedrohmg1/La-Casa-De-Sacola-web -b main
